### ISSUE TITLE
EGit Merge tool doesn't work with XtextEditor

### ISSUE THREAD

**Issue by rheydenr** [eclipse/xtext-eclipse#1208]
Steps to reproduce:

- create an Xtext project (with at least one Xtext document) and add it to a Git repository
- on master branch: change the Xtext document and commit it
- switch to another branch (cloned from master) and change the same Xtext document (with another modification which should provoke a merge conflict with master branch's file), commit it
- merge branch master into the current branch so that a merge conflict occurs
- use *Team -> Merge Tool* on that Xtext document
The following exception is thrown:
```
Caused by: org.eclipse.ui.PartInitException: Editor could not be initialized.
	at org.eclipse.ui.texteditor.AbstractTextEditor.internalInit(AbstractTextEditor.java:3188)
	at org.eclipse.ui.texteditor.AbstractTextEditor.init(AbstractTextEditor.java:3197)
	at org.eclipse.xtext.ui.editor.XtextEditor.init(XtextEditor.java:305)
	at org.eclipse.xtext.ui.compare.DefaultMergeViewer.createSourceViewerConfiguration(DefaultMergeViewer.java:190)
	... 62 more
Caused by: java.lang.IllegalArgumentException: document may not be null
	at org.eclipse.xtext.ui.editor.DocumentBasedDirtyResource.connect(DocumentBasedDirtyResource.java:36)
	at org.eclipse.xtext.ui.editor.DirtyStateEditorSupport.initDirtyResource(DirtyStateEditorSupport.java:448)
	at org.eclipse.xtext.ui.editor.DirtyStateEditorSupport.initializeDirtyStateSupport(DirtyStateEditorSupport.java:390)
	at org.eclipse.xtext.ui.editor.XtextEditor.initializeDirtyStateSupport(XtextEditor.java:278)
	at org.eclipse.xtext.ui.editor.XtextEditor.doSetInput(XtextEditor.java:260)
	at org.eclipse.xtext.ui.compare.DefaultMergeEditor.doSetInput(DefaultMergeEditor.java:43)
	at org.eclipse.ui.texteditor.AbstractTextEditor$5.run(AbstractTextEditor.java:3154)
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:437)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:353)
	at org.eclipse.ui.internal.WorkbenchWindow$14.run(WorkbenchWindow.java:2195)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.internal.WorkbenchWindow.run(WorkbenchWindow.java:2191)
	at org.eclipse.ui.texteditor.AbstractTextEditor.internalInit(AbstractTextEditor.java:3172)
	... 65 more
```
It seems that the Merge Tool uses a `StreamContentDocumentProvider` instead of an `XtextDocumentProvider` so that only a plain JFace document object is created.

**Comment by tomaswolf** [comment]
Which EGit version? Which Xtext version? What's set as input for the merge tool? If it's "Last HEAD (unmerged)", then https://bugs.eclipse.org/bugs/show_bug.cgi?id=550989 might be related. That bug is fixed in EGit nightly, which can be installed from the update site https://download.eclipse.org/egit/updates-nightly .

**Comment by rheydenr** [comment]
EGit: 5.5.1
Xtext: 2.19
Input for the merge tool is an Xtext document file. Bug #550989 seems to be another topic.

**Comment by tomaswolf** [comment]
Yes, the merge conflict is on an Xtext file. But what is set at "Preferences->Team->Git", "Merge Tool content"? If that is set to "Last HEAD (unmerged)", please try with EGit nightly.

The fix for bug 550989 had to do with making Eclipse select the right document provider, so it may well be that this is the same case.

**Comment by cdietrich** [comment]
@tomaswolf 

 the problem is still there in
Eclipse EGit	Git integration for Eclipse	5.5.1.201910021850-r	org.eclipse.egit

but is not in 
Eclipse EGit	Git integration for Eclipse	5.6.0.201910081857	org.eclipse.egit

but the merge tool left side is empty which seems wrong

![Bildschirmfoto vom 2019-10-09 08-51-35](https://user-images.githubusercontent.com/238736/66458041-06a29380-ea72-11e9-9a38-fc038f16720a.png)

**Comment by rheydenr** [comment]
With EGit nightly there's a missing reference to `org.eclipse.jgit.transport.http.apache`. With nightly-stable the following error occurs:
```
Caused by: org.eclipse.ui.PartInitException: Editor could not be initialized.
	at org.eclipse.ui.texteditor.AbstractTextEditor.internalInit(AbstractTextEditor.java:3188)
	at org.eclipse.ui.texteditor.AbstractTextEditor.init(AbstractTextEditor.java:3197)
	at org.eclipse.xtext.ui.editor.XtextEditor.init(XtextEditor.java:305)
	at org.eclipse.xtext.ui.compare.DefaultMergeViewer.createSourceViewerConfiguration(DefaultMergeViewer.java:190)
	... 62 more
Caused by: java.lang.IllegalArgumentException: document may not be null
	at org.eclipse.xtext.ui.editor.DocumentBasedDirtyResource.connect(DocumentBasedDirtyResource.java:36)
	at org.eclipse.xtext.ui.editor.DirtyStateEditorSupport.initDirtyResource(DirtyStateEditorSupport.java:448)
	at org.eclipse.xtext.ui.editor.DirtyStateEditorSupport.initializeDirtyStateSupport(DirtyStateEditorSupport.java:390)
	at org.eclipse.xtext.ui.editor.XtextEditor.initializeDirtyStateSupport(XtextEditor.java:278)
	at org.eclipse.xtext.ui.editor.XtextEditor.doSetInput(XtextEditor.java:260)
	at org.eclipse.xtext.ui.compare.DefaultMergeEditor.doSetInput(DefaultMergeEditor.java:43)
	at org.eclipse.ui.texteditor.AbstractTextEditor$5.run(AbstractTextEditor.java:3154)
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:437)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:353)
	at org.eclipse.ui.internal.WorkbenchWindow$14.run(WorkbenchWindow.java:2195)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.internal.WorkbenchWindow.run(WorkbenchWindow.java:2191)
	at org.eclipse.ui.texteditor.AbstractTextEditor.internalInit(AbstractTextEditor.java:3172)
	... 65 more
```

**Comment by tomaswolf** [comment]
> missing reference to `org.eclipse.jgit.transport.http.apache`.

Then something went wrong with the upgrade. When I upgrade, it does include that. Make sure the JGit support for Apache HTTP is also checked when installing. (Sometimes the update mechanism works better if it gets a little manual help.)

**Comment by cdietrich** [comment]
@rheydenr regaring installing the nighty:

just adding the update site and check for updates worked for me

**Comment by rheydenr** [comment]
Ok, you are right :-) I'm using a tpd file for the target platform, there was a missing plugin. Now I have a working environment. The Exception does not occur anymore, but now I have the same error as @cdietrich, where the left pane is completely empty. It is the case if you switch to text compare view, too.

**Comment by tomaswolf** [comment]
Yes, left side comes up empty. That's due to an NPE, which was pointed out in https://bugs.eclipse.org/bugs/show_bug.cgi?id=550989 already. The left side is an IStorage that represents a git index entry. This storage returns `null` in getFullPath(). This is allowed; see the javadoc of IStorage.getFullPath(). In fact, EGit _must_ return `null` there.

Xtext then runs into an NPE at [ResourceForIEditorInputFactory.createResourceFor()](https://github.com/eclipse/xtext-eclipse/blob/master/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/ResourceForIEditorInputFactory.java#L110), and the result is that empty left pane.

**Comment by cdietrich** [comment]
@szarnekow do you have any idea how we could deal with null here?

**Comment by tomaswolf** [comment]
The basic problem is that there is no on-disk resource or whatever for the IStorage.

**Comment by tomaswolf** [comment]
Two thoughts:

1. Why does ResourceForIEditorInputFactory not use the Storage2UriMapper to get a URI for the storage?
2. Would still have to handle the case of a null URI. Maybe assign the storage (or rather, the resource created for it) some internal in-memory URI?

**Comment by szarnekow** [comment]
The URI is used to figure the correct EMF resource factory / resource implementation. The storage 2 uri mapper is merely a cache for storages that do exist physically on disk, e.g. reside in JAR files. It won't provide URIs for demand created revision storages.

**Comment by szarnekow** [comment]
We certainly need a file extension to figure at least some sensible resource impl.

**Comment by szarnekow** [comment]
The situation will likely be improved when we do no longer use the FileDocumentProvider.

**Comment by tomaswolf** [comment]
The file extension of the storage is available via IStorage.getName().

**Comment by szarnekow** [comment]
True, though it's documented as being nullable, too :(

**Comment by tomaswolf** [comment]
Right. :-(

Just for completeness' sake: that's the stack trace I get (when debugging; it isn't logged anywhere):
```
org.eclipse.core.runtime.CoreException: 
	at org.eclipse.xtext.ui.editor.model.XtextDocumentProvider.setDocumentResource(XtextDocumentProvider.java:226)
	at org.eclipse.xtext.ui.editor.model.XtextDocumentProvider.setDocumentContent(XtextDocumentProvider.java:194)
	at org.eclipse.ui.editors.text.StorageDocumentProvider.createDocument(StorageDocumentProvider.java:225)
	at org.eclipse.xtext.ui.editor.model.XtextDocumentProvider.createDocument(XtextDocumentProvider.java:149)
	at org.eclipse.ui.editors.text.StorageDocumentProvider.createElementInfo(StorageDocumentProvider.java:254)
	at org.eclipse.ui.editors.text.FileDocumentProvider.createElementInfo(FileDocumentProvider.java:736)
	at org.eclipse.xtext.ui.editor.model.XtextDocumentProvider.createElementInfo(XtextDocumentProvider.java:270)
	at org.eclipse.ui.texteditor.AbstractDocumentProvider.connect(AbstractDocumentProvider.java:395)
	at org.eclipse.ui.texteditor.AbstractTextEditor.doSetInput(AbstractTextEditor.java:4167)
	at org.eclipse.ui.texteditor.StatusTextEditor.doSetInput(StatusTextEditor.java:260)
	at org.eclipse.ui.texteditor.AbstractDecoratedTextEditor.doSetInput(AbstractDecoratedTextEditor.java:1476)
	at org.eclipse.ui.editors.text.TextEditor.doSetInput(TextEditor.java:153)
	at org.eclipse.xtext.ui.editor.XtextEditor.doSetInput(XtextEditor.java:259)
	at org.eclipse.xtext.ui.compare.DefaultMergeEditor.doSetInput(DefaultMergeEditor.java:43)
	at org.eclipse.ui.texteditor.AbstractTextEditor.lambda$1(AbstractTextEditor.java:3135)
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:440)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:356)
	at org.eclipse.ui.internal.WorkbenchWindow.lambda$3(WorkbenchWindow.java:2254)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:72)
	at org.eclipse.ui.internal.WorkbenchWindow.run(WorkbenchWindow.java:2252)
	at org.eclipse.ui.texteditor.AbstractTextEditor.internalInit(AbstractTextEditor.java:3152)
	at org.eclipse.ui.texteditor.AbstractTextEditor.init(AbstractTextEditor.java:3177)
	at org.eclipse.xtext.ui.editor.XtextEditor.init(XtextEditor.java:305)
	at org.eclipse.xtext.ui.compare.DefaultMergeViewer.createSourceViewerConfiguration(DefaultMergeViewer.java:190)
	at org.eclipse.xtext.ui.compare.DefaultMergeViewer.configureSourceViewer(DefaultMergeViewer.java:168)
	at org.eclipse.xtext.ui.compare.DefaultMergeViewer.configureTextViewer(DefaultMergeViewer.java:162)
	at org.eclipse.compare.contentmergeviewer.TextMergeViewer.configureSourceViewer(TextMergeViewer.java:3002)
	at org.eclipse.compare.contentmergeviewer.TextMergeViewer.updateContent(TextMergeViewer.java:2950)
	at org.eclipse.xtext.ui.compare.DefaultMergeViewer.updateContent(DefaultMergeViewer.java:100)
	at org.eclipse.compare.contentmergeviewer.ContentMergeViewer.internalRefresh(ContentMergeViewer.java:784)
	at org.eclipse.compare.contentmergeviewer.ContentMergeViewer.inputChanged(ContentMergeViewer.java:692)
	at org.eclipse.jface.viewers.ContentViewer.setInput(ContentViewer.java:289)
	at org.eclipse.compare.CompareViewerSwitchingPane.setInput(CompareViewerSwitchingPane.java:268)
	at org.eclipse.compare.internal.CompareContentViewerSwitchingPane.setInput(CompareContentViewerSwitchingPane.java:183)
	at org.eclipse.compare.CompareEditorInput.internalSetContentPaneInput(CompareEditorInput.java:798)
	at org.eclipse.compare.CompareEditorInput.lambda$8(CompareEditorInput.java:746)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:72)
	at org.eclipse.compare.CompareEditorInput.feed1(CompareEditorInput.java:734)
	at org.eclipse.compare.CompareEditorInput.lambda$4(CompareEditorInput.java:632)
	at org.eclipse.compare.CompareViewerPane.open(CompareViewerPane.java:312)
	at org.eclipse.jface.viewers.StructuredViewer$2.run(StructuredViewer.java:853)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:47)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:176)
	at org.eclipse.jface.viewers.StructuredViewer.fireOpen(StructuredViewer.java:850)
	at org.eclipse.compare.structuremergeviewer.DiffTreeViewer.internalOpen(DiffTreeViewer.java:689)
	at org.eclipse.compare.structuremergeviewer.DiffTreeViewer.access$3(DiffTreeViewer.java:686)
	at org.eclipse.compare.structuremergeviewer.DiffTreeViewer$1.openSelectedChange(DiffTreeViewer.java:224)
	at org.eclipse.compare.internal.CompareEditorInputNavigator.openElement(CompareEditorInputNavigator.java:99)
	at org.eclipse.compare.internal.CompareEditorInputNavigator.selectChange(CompareEditorInputNavigator.java:68)
	at org.eclipse.egit.ui.internal.merge.GitMergeEditorInput.contentsCreated(GitMergeEditorInput.java:267)
	at org.eclipse.compare.CompareEditorInput.createContents(CompareEditorInput.java:561)
	at org.eclipse.compare.internal.CompareEditor.createCompareControl(CompareEditor.java:444)
	at org.eclipse.compare.internal.CompareEditor.access$6(CompareEditor.java:404)
	at org.eclipse.compare.internal.CompareEditor$1.lambda$0(CompareEditor.java:362)
	at org.eclipse.ui.internal.PendingSyncExec.run(PendingSyncExec.java:61)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:171)
	at org.eclipse.ui.internal.UISynchronizer.lambda$0(UISynchronizer.java:153)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4068)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3735)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:628)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)
Caused by: java.lang.NullPointerException
	at org.eclipse.xtext.ui.editor.model.ResourceForIEditorInputFactory.createResourceFor(ResourceForIEditorInputFactory.java:110)
	at org.eclipse.xtext.ui.editor.model.ResourceForIEditorInputFactory.createResource(ResourceForIEditorInputFactory.java:105)
	at org.eclipse.xtext.ui.editor.model.JavaClassPathResourceForIEditorInputFactory.createResource(JavaClassPathResourceForIEditorInputFactory.java:51)
	at org.eclipse.xtext.ui.editor.model.ResourceForIEditorInputFactory.createResource(ResourceForIEditorInputFactory.java:77)
	at org.eclipse.xtext.ui.editor.model.XtextDocumentProvider.setDocumentResource(XtextDocumentProvider.java:214)
	... 83 more
```

**Comment by szarnekow** [comment]
> `ResourceForIEditorInputFactory.createResource(ResourceForIEditorInputFactory.java:77)`

Here we do have the IEditorInput with a (documented to be) non-null name.

**Comment by tomaswolf** [comment]
> Here we do have the IEditorInput with a (documented to be) non-null name.

A non-null name all right, but not necessarily a file name.

**Comment by tomaswolf** [comment]
I see two possibilities:

1. Quick hack: use IStorage.getName() if IStorage.getFullPath() returns null. If both are null, give up.
2. The document provider _also_ was chosen by Eclipse (DocumentProviderRegistry) based on a file name extension. So either let the document provider for a language know how to create resources (probably a rather invasive change), or use in ResourceForIEditorInputFactory similar logic as in DocumentProviderRegistry:

```
IFile file= editorInput.getAdapter(IFile.class);
if (file != null) {
	provider= getDocumentProvider(file.getFileExtension());
} else {
	IPathEditorInput pathInput= Adapters.adapt(editorInput, IPathEditorInput.class);
	if (pathInput != null) {
		IPath path= pathInput.getPath();
		if (path != null) {
			provider= getDocumentProvider(path.getFileExtension());
		}
	}
}
```

**Comment by tomaswolf** [comment]
I don't have a full xtext development environment set up so I can't provide you with a fully tested PR including maybe even a test, but the above suggestion actually works.

Change ResourceForIEditorInputFactory.createResource(IEditorInput editorInput) to
```
if (editorInput instanceof IStorageEditorInput) {
    IStorage storage = ((IStorageEditorInput) editorInput).getStorage();
    IPath path = storage.getFullPath();
    if (path == null) {
        IFile file = editorInput.getAdapter(IFile.class);
        if (file != null) {
            path = file.getFullPath();
        } else {
            IPathEditorInput pathInput = Adapters.adapt(editorInput, IPathEditorInput.class);
            if (pathInput != null) {
                path = pathInput.getPath();
            }
        }
    }
    Resource result = createResource(storage, path);
    ...
```
and pass through the IPath to createResource and createResourceFor, then use it there. If you want you could as an additional safeguard use in createResourceFor storage.getName() if the path == null.

With that change, Xtext can open these IStorages from EGit.

**Comment by tomaswolf** [comment]
Any chance that this gets fixed in the Xtext version that'll go into Eclipse 2019-12?

**Comment by cdietrich** [comment]
I don’t know if I will find the time to look into it yet
